### ISSUE TITLE
[Request] Option to add sub-zone location names to the map

### ISSUE THREAD

**Issue by capSAR273** [MidoriKami/Mappy#71] opened 2024-01-21 17:08 UTC
For example, the vanilla map for Eastern Thanalan looks like this:
![image](https://github.com/MidoriKami/Mappy/assets/5252505/57c13424-15c1-4227-97a6-62201b324e54)
While Mappy's version looks like:
![image](https://github.com/MidoriKami/Mappy/assets/5252505/267bdd93-9c15-4ac1-981e-6b0013eb78c1)

Having "Drybone" and "Sandgate" etc on the map is helpful for newer players doing hunting log or other activities that tell you the smaller location names. Mappy doesn't have this as far as I know, I looked through the configuration options but didn't see it so if I missed it please let me know! Thank you so much for your hard work on Mappy, once I discovered it I don't want to go without it <3

**Comment by MidoriKami** [comment] 2024-01-21 17:22
Duplicate of #50
I have attempted to add this text in the past and it does not look good nor perform well.

In Hunting Logs if you click on the text that says "Drybone" or "Sandgate" Mappy will open to that location.

Additionally there is a search function in Mappy that does search by sub-location name.

**Closed by MidoriKami** 2024-01-21 17:22 UTC
