### ISSUE TITLE
[bug?] When quest is marked as "ignored" in journal, Mappy doesn't map it correctly

### ISSUE THREAD

**Issue by imcleo** [MidoriKami/Mappy#56] opened 2023-09-29 21:29 UTC
Instead it seems to place a marker in the center of the map. Un-ignoring the quest will cause the correct marker to appear but the incorrect marker will remain.

**Comment by MidoriKami** [comment] 2023-09-29 21:30
Right click the marker, you'll see an option to dismiss it, it's not a normal quest marker.

**Comment by imcleo** [comment] 2023-09-29 21:43
When quest is ignored and "map" button is pressed:
![2023-09-29 (2)](https://github.com/MidoriKami/Mappy/assets/57550518/fcba1653-efa2-41e7-85b6-7fc5ed2b34b0)

After un-ignoring quest, the correct marker appears, but the incorrect one remains:
![2023-09-29 (3)](https://github.com/MidoriKami/Mappy/assets/57550518/eb2dc23f-86d9-4ee8-a880-323acc489db2)

**Comment by MidoriKami** [comment] 2023-09-29 22:08
Right click the marker, you'll see an option to dismiss it, it's not a normal quest marker.

The location error is a duplicate of https://github.com/MidoriKami/Mappy/issues/44

**Closed by MidoriKami** 2023-09-29 22:08 UTC

**Comment by imcleo** [comment] 2023-09-29 22:11
I disagree that it's a duplicate, in the first screenshot the correct quest marker does not appear at all. Only when the quest is un-ignored does it appear.

**Comment by MidoriKami** [comment] 2023-09-29 22:20
This isn't up for debate, I'm the one that literally designed this system.

Once again I regret providing explanation and people feeling the need to argue with me.
The marker with the blue circle is being put in the wrong location because of #44. 

The marker with the blue circle is a completely separate system than the regular quest markers. It ignores the quest log settings because that's how it needs to work.
