### ISSUE TITLE
[Bug] Blue unlock "continuation" quest markers missing

### ISSUE THREAD

**Issue by sersorrel** [MidoriKami/Mappy#21] opened 2023-07-14 22:38 UTC
If you're partway through a quest you get markers like these:

![image](https://github.com/MidoriKami/Mappy/assets/9433472/8090e4d1-f9f4-4a61-b5ea-6d8dff99dfd9)

but they don't show up in Mappy:

![image](https://github.com/MidoriKami/Mappy/assets/9433472/77db88a1-0150-441b-990e-be9b944e47d6)

(this one is Dramatis Personae, the first Ivalice quest; I've spoken to Lina once so far and now need to do so again, iirc)

I'm using Mappy 1.0.0.9.

**Comment by MidoriKami** [comment] 2023-07-14 23:12
Are you able to reproduce this with any other quest?

**Comment by sersorrel** [comment] 2023-07-15 00:30
hmmmmmm, I accepted The New King on the Block (also found in Kugane) to check, and now suddenly Dramatis Personae is showing up in Mappy... I'm not 100% sure whether that happened when I zoned back into Kugane or when I accepted TNKotB, though.

The second stage of TNKotB ("gather information", talk to 3 NPCs) displays an area with the question mark symbol (I think actually three layered areas? the tooltip is repeated three times, at least, and one layer disappears each time you talk to an NPC):

![image](https://github.com/MidoriKami/Mappy/assets/9433472/07e3ab54-a477-4727-8bff-7d0f31204b8f)

Then the marker for the third stage ("Speak with the concerned Qestiri merchant") shows up fine:

![image](https://github.com/MidoriKami/Mappy/assets/9433472/655fc0b4-6c00-463c-af07-cf5aa1bd3052)

And even after abandoning TNKotB, the marker for Dramatis Personae is still correctly appearing in Mappy, so I'm not sure what was going on earlier. The only thing I can think of is maybe some conflict with QuestAWAY?? I have it set to hide the repeating unlock quest icon in Idyllshire specifically, and iirc I installed Mappy today while in Idyllshire, but that's not the icon we're looking at here, and I can't seem to reproduce the problem by disabling/enabling Mappy in Idyllshire, so I guess that must be unrelated.

Just the game being weird I guess ¯\\_(ツ)\_/¯

**Comment by MidoriKami** [comment] 2023-07-15 00:36
Hmm, QuestAway shouldn't be able to effect things unless it's changing the data in the recently RE'd Map datastructures (that aren't even merged publicly yet)

I even ignore the users setting to show/hide quests hehe/

**Closed by MidoriKami** 2023-07-15 00:36 UTC
Labels: bug

**Comment by MidoriKami** [comment] 2023-07-15 21:30
Follow-up information, it seems that in specific circumstances the game doesn't populate the quest data array.
There is nothing that Mappy can do at this time get the correct data.

It appears the fix is to simply accept another quest to force the game to re-populate the quest data.

**Comment by MidoriKami** [comment] 2023-07-22 19:05
Turns out the actual bug has to do with the QuestSpan, The game gives us 30 slots for quests, and I assumed it would fill those slots in order, so I only grab the first X slots, where X is how many quests you have accepted.

This is not the case, sometimes you will have 1 quest accepted, but that quest will be in the 2nd slot in the span. Mappy was only looking at the first slot and going "?? there's nothing here"
